### ISSUE TITLE
Does not work in the shell as the instructions say.

### ISSUE THREAD

**Issue by darkcohiba** [learn-co-curriculum/python-p3-import#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/215884?module_item_id=502461

### Concern

`samuelwaters@Samuel-Waters-MacBook-Pro python-p3-import % pipenv shell
Launching subshell in virtual environment...
 . /Users/samuelwaters/.local/share/virtualenvs/python-p3-import-tb5SXTka/bin/activate
samuelwaters@Samuel-Waters-MacBook-Pro python-p3-import %  . /Users/samuelwaters/.local/share/virtualenvs/python-p3-i
mport-tb5SXTka/bin/activate
(python-p3-import) samuelwaters@Samuel-Waters-MacBook-Pro python-p3-import %  import os
 os.name
zsh: command not found: import
zsh: command not found: os.name`

I tried to run the code given in the example in the Shell but it was not recognized. I put it inside the module1.py and slightly altered the code 

`import os
print (os.name)`

Then ran it in the terminal and it printed the name as expected but following the directions did not work. Was I not supposed to run it in the shell as described? I am confused by the instructions.

**Comment by professor-ben** [comment]
Hey Sam,

We added something to clarify to open the Python shell- that should fix this issue. Sorry we forgot to update and thanks for looping us in!

-Ben
